# Container based on https://www.docker.com/blog/how-to-dockerize-react-app/
# Base
FROM node:26-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# Dev server
FROM base AS dev
EXPOSE 3000
CMD ["npm", "start"]

# Build
FROM base AS build
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
COPY . .
RUN npm run build

# Release
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]