services:
  server:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"

  app:
    build: 
      context:
        ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - server